# Generated by Django 4.0.3 on 2022-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_post_options_post_title_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='users/%Y/%m'),
        ),
    ]
