# Generated by Django 4.0.3 on 2022-04-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.post'),
        ),
    ]
