# Generated by Django 4.0.3 on 2022-04-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_post_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.post'),
        ),
    ]
