# Generated by Django 4.0.3 on 2022-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_postdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
